### ISSUE TITLE
Project E Textures

### ISSUE THREAD

**Issue by IronPiston** [scottkillen-minecraft-textures/Isabella-II-FTB#1]
Having never used Github, I have no idea how to contribute some Project E textures, but I do have quite a few done. I know this isn't an issue, but I don't know how to properly use pull requests
https://www.dropbox.com/s/4xuuf7wv3g1pdah/projecte.zip?dl=0

**Comment by Akull9** [comment]
I added you as a collaborator to the repo, meaning you can commit to it. I also added your textures when you posted them to the Isabella forum post...
