### ISSUE TITLE
Donwload Zip not up to date

### ISSUE THREAD

**Issue by Oaurn** [scottkillen-minecraft-textures/Isabella-II-FTB#3]
Pretty much what it says.  I love your textures, and you do a great job making them fit the theme of the Isabella 2 texture pack, but some of the updates you have done specifically the updated thermal expansion GUI's are not in the pack when you download it.

Just thought I should bring this to you attention.   I've downloaded it several time just to rule out an issue on my end, but the old files are still there.

Thanks

**Comment by Akull9** [comment]
It should be fixed now; I had to update the releases... Glad you like the textures!
